name = "zola-tailwind"
description = "A Zola theme made with Tailwindcss"
license = "MIT"
homepage = "https://github.com/lerte/zola-tailwind"
# The minimum version of Zola required
min_version = "0.9.0"
# An optional live demo URL
demo = "https://tchartron.com"

# The theme author info: you!
[author]
name = "Lerte Smith"
homepage = "https://hugola.app"

[extra]
enable_search = true
enable_sidebar = true
enable_adsense = true
enable_multilingue = true
adsense_link = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=myclientid"

[extra.lang]
items = [
    { lang = "en", links = [
        { base_url = "/", name = "English" },
        { base_url = "/cn", name = "中文简体" }
    ] },
    { lang = "cn", links = [
        { base_url = "/", name = "English" },
        { base_url = "/cn", name = "中文简体" }
    ] }
]

[extra.navbar]
title = "title"
items = [
    { lang = "en", links = [
        { url = "/", name = "Home" },
        { url = "/categories", name = "Categories" },
        { url = "/tags", name = "Tags" }
    ] },
    { lang = "cn", links = [
        { url = "/cn", name = "首页" },
        { url = "/cn/categories", name = "分类" },
        { url = "/cn/tags", name = "标签" }
    ] }
]

[extra.sidebar]
items = [
    { lang = "en", links = [
        { url = "/markdown", name = "Markdown" },
        { url = "/blog", name = "Blog" }
    ] },
    { lang = "cn", links = [
        { url = "/cn/markdown", name = "Markdown" },
        { url = "/cn/blog", name = "Blog" }
    ] }
]

# Index page
[extra.index]
title = "Main title"
image = "https://via.placeholder.com/200"
image_alt = "Placeholder text describing the index's image."

[extra.default_author]
name = "Lerte Smith"
avatar = "https://via.placeholder.com/200"
avatar_alt = "Placeholder text describing the default author's avatar."

[extra.social]
github = "https://github.com/lerte"
gitlab = "https://gitlab.com/lerte"
twitter = "https://twitter.com/taildoor"
linkedin = "https://www.linkedin.com/in/lerte/"
email = "lertesmith@gmail.com"


[extra.favicon]
favicon = "/icons/favicon.ico"
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
android_chrome_512 = "/icons/android-chrome-512x512.png"
android_chrome_192 = "/icons/android-chrome-192x192.png"
manifest = "/icons/site.webmanifest"
